persistence:
  enabled: true
  storageClass: "local-path"
  size: 1Gi

replicaCount: 3

auth:
  rbac:
    create: false

removeMemberOnContainerTermination: false

initialClusterState: "new"

configuration:
  max-txn-ops: "200000"
