persistence:
  enabled: true
  storageClass: "local-path"
  size: 8Gi

replicaCount: 3

auth:
  rbac:
    create: false

removeMemberOnContainerTermination: false

resources:
  limits:
    cpu: 375m
    ephemeral-storage: 2Gi
    memory: 768Mi
  requests:
    cpu: 250m
    ephemeral-storage: 50Mi
    memory: 768Mi

autoCompactionMode: revision
autoCompactionRetention: "100"

extraEnvVars:
  - name: ETCD_MAX_TXN_OPS
    value: "200000"
  - name: ETCD_QUOTA_BACKEND_BYTES
    value: "8589934592"

podAntiAffinityPreset: "hard"

preUpgradeJob:
  annotations:
    "helm.sh/hook-delete-policy": "hook-succeeded"
