persistence:
  enabled: true
  storageClass: "local-path"
  size: 1Gi

replicaCount: 0

auth:
  rbac:
    create: false

removeMemberOnContainerTermination: false

initialClusterState: "new"

extraEnvVars:
  - name: ETCD_MAX_TXN_OPS
    value: "200000"

resources:
  limits:
    cpu: 375m
    ephemeral-storage: 2Gi
    memory: 768Mi
  requests:
    cpu: 250m
    ephemeral-storage: 50Mi
    memory: 768Mi
