apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: rook-ceph
  releaseName: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      version: "v1.17.4"
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    allowLoopDevices: true
    scaleDownOperator: false
    csi:
      enableRBDSnapshotter: true
    monitoring:
      enabled: true
