apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@gitlab.com:alexclear/not-so-awesome-argocd-infra.git
    targetRevision: main
    path: applicationsets
    directory:
      recurse: false
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
