apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-applications
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@gitlab.com:alexclear/not-so-awesome-argocd-infra.git
      revision: main
      directories:
      - path: applications-helm/**/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: git@gitlab.com:alexclear/not-so-awesome-argocd-infra.git
        targetRevision: 'main'
        path: '{{path}}'
        plugin: {}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/2/clientConfig/caBundle
        - /webhooks/3/clientConfig/caBundle
        - /webhooks/4/clientConfig/caBundle
        - /webhooks/5/clientConfig/caBundle
        - /webhooks/6/clientConfig/caBundle
        - /webhooks/7/clientConfig/caBundle
        - /webhooks/8/clientConfig/caBundle
        - /webhooks/9/clientConfig/caBundle
        - /webhooks/10/clientConfig/caBundle
        - /webhooks/11/clientConfig/caBundle
        - /webhooks/12/clientConfig/caBundle
        - /webhooks/13/clientConfig/caBundle
