---
apiVersion: control.vitastor.io/v1
kind: VitastorPool
metadata:
  name: vitastor-3-test-pool
spec:
  scheme: "replicated"
  failureDomain: "osd"
  id: "4"
  pgCount: 64
  pgMinSize: 2
  pgSize: 3
  immediateCommit: "none"
