apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 5m
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      version: "2.17.3"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      interval: 1m
  targetNamespace: sealed-secrets
  install:
    createNamespace: true
  values:
    fullnameOverride: sealed-secrets-controller
