---
apiVersion: v1
kind: ConfigMap
data:
  vitastor.conf: |-
    {"etcd_address":["10.43.235.120:2379"],
    "etcd_prefix": "/vitastor",
    "osd_network": "10.238.0.0/16",
    "bind_port": "5666"
    }
metadata:
  namespace: vitastor-system
  name: vitastor-config
