apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: forgejo-dockerless-runner
spec:
  serviceName: forgejo-dockerless-runner
  replicas: 1
  selector:
    matchLabels:
      app: forgejo-dockerless-runner
  template:
    metadata:
      labels:
        app: forgejo-dockerless-runner
    spec:
      restartPolicy: Always
      containers:
        - name: runner
          image: gitinsky/dockerless-forgejo-runner:1aa85b5
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
          env:
            - name: FORGEJO_URL
              value: "https://forgejo-pve1.spbnix.local"
          volumeMounts:
            - name: runner-data
              mountPath: /home/forgejo/data
            - name: tmp-volume
              mountPath: /tmp
            - name: local-share
              mountPath: /home/forgejo/.local
      volumes:
        - name: runner-data
          emptyDir: {}
        - name: tmp-volume
          emptyDir: {}
        - name: local-share
          emptyDir: {}
