apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: forgejo-dockerless-runner
spec:
  serviceName: forgejo-dockerless-runner
  replicas: 1
  selector:
    matchLabels:
      app: forgejo-dockerless-runner
  template:
    metadata:
      labels:
        app: forgejo-dockerless-runner
    spec:
      restartPolicy: Always
      containers:
        - name: runner
          image: gitinsky/dockerless-forgejo-runner:625aaba
          securityContext:
            privileged: true
            readOnlyRootFilesystem: true
          env:
            # Set as needed, e.g. for Forgejo instance, runner name, etc.
            # - name: FORGEJO_INSTANCE_URL
            #   value: "http://forgejo.example.com"
          volumeMounts:
            - name: runner-data
              mountPath: /home/forgejo/data
            - name: tmp-volume
              mountPath: /tmp
            - name: local-share
              mountPath: /home/forgejo/.local
      volumes:
        - name: runner-data
          emptyDir: {}
        - name: tmp-volume
          emptyDir: {}
        - name: local-share
          emptyDir: {}
