repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: kube-prometheus-stack
  chart: prometheus-community/kube-prometheus-stack
  version: 68.3.0
  values:
  - ./values.yaml
  jsonPatches:
  - target:
      version: v1
      kind: CustomResourceDefinition
      name: prometheuses.monitoring.coreos.com
    patch:
    - op: add
      path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
      value: "ServerSideApply=true"
  - target:
      version: v1
      kind: CustomResourceDefinition
      name: prometheusagents.monitoring.coreos.com
    patch:
    - op: add
      path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
      value: "ServerSideApply=true"
  - target:
      version: v1
      kind: CustomResourceDefinition
      name: scrapeconfigs.monitoring.coreos.com
    patch:
    - op: add
      path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
      value: "ServerSideApply=true"
