speaker:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 100Mi

controller:
  resources:
    requests:
      cpu: 15m
      memory: 200Mi
    limits:
      cpu: 100m
      memory: 200Mi
