engines:
  local:
    lvm:
      enabled: false
    zfs:
      enabled: false
  replicated:
    mayastor:
      enabled: true

loki:
  enabled: false
  minio:
    enabled: false

alloy:
  enabled: false

mayastor:
  etcd:
    extraEnvVars:
    - name: ETCD_INITIAL_CLUSTER_STATE
      value: existing
  loki-stack:
    enabled: false
  localpv-provisioner:
    enabled: false
  storageClass:
    enabled: true
    nameSuffix: three-replicas
    default: false
    allowVolumeExpansion: true
    parameters:
      protocol: nvmf
      repl: 3
