apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-grafana-passwords
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mysql-grafana-passwords
  dataFrom:
  - extract:
      key: mysql-grafana-passwords
      metadataPolicy: None
      conversionStrategy: Default
      decodingStrategy: None
