apiVersion: operator.victoriametrics.com/v1beta1
kind: VLogs
metadata:
  name: vlogs-ms
spec:
  retentionPeriod: "10d"

  image:
    tag: v1.23.3-victorialogs

  resources:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 1Gi

  storage:
    storageClassName: "openebs-three-replicas"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi
