apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-s3-wals
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-s3-wals
  dataFrom:
  - extract:
      key: grafana-s3-wals
      metadataPolicy: None
      conversionStrategy: Default
      decodingStrategy: None
