role: Agent
dataDir: /vector-data-dir
args:
  - -w
  - --config-dir
  - /etc/vector/
containerPorts:
  - name: prom-exporter
    containerPort: 9090
    protocol: TCP
service:
  enabled: false
customConfig:
  data_dir: /vector-data-dir
  api:
    enabled: false
    address: 0.0.0.0:8686
    playground: true
  sources:
    k8s:
      type: kubernetes_logs
    internal_metrics:
      type: internal_metrics
  transforms:
    parser:
      type: remap
      inputs: [k8s]
      source: |
        .log = parse_json(.message) ?? .message
        del(.message)
  sinks:
    exporter:
      type: prometheus_exporter
      address: 0.0.0.0:9090
      inputs: [internal_metrics]
    vlogs:
      type: elasticsearch
      inputs: [parser]
      endpoints: [http://vlogs-vlogs-vs-3.victorialogs.svc.cluster.local:9428/insert/elasticsearch/]
      mode: bulk
      api_version: v8
      batch:
        max_bytes: 1048576
        max_events: 500 
      compression: gzip
      request:
        headers:
          VL-Time-Field: timestamp
          VL-Stream-Fields: stream,kubernetes.pod_name,kubernetes.container_name,kubernetes.pod_namespace
          VL-Msg-Field: message,msg,_msg,log.msg,log.message,log
          AccountID: "0"
          ProjectID: "0"
