vpa:
  enabled: true

metrics-server:
  enabled: true
  extraArgs:
    - --kubelet-insecure-tls=true
    - --kubelet-preferred-address-types=InternalIP

controller:
  resources:
    limits:
      cpu: 130m
      memory: 150Mi
    requests:
      cpu: 130m
      memory: 150Mi
  rbac:
    extraRules:
      - apiGroups:
          - 'batch'
        resources:
          - 'cronjobs'
          - 'jobs'
        verbs:
          - 'list'

dashboard:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: goldilocks.k8s.ggcorp.ru
        paths:
          - path: /
            type: ImplementationSpecific
